export const scopifyByOpenAiPromt: string[] = [
  "Define the regional geographic relevance based on the provided information.",
  "Respond with JSON matching this interface:",
  "interface Scope {\n      relevance: 'tight-nearby' | 'wider-region' | 'specific-location' | 'formal-municipality' | 'unknown';\n    }",
  "Use this boosting logic:",
  "- 'timespan': Multi day tends to a wider relevance; e.g. 2d are likely relevant for a 'wider-region'.",
  "- 'timespan': Shorter timespan tends to a tighter relevance; e.g. 30min is more likely 'specific-location', 1h is more likely 'tight-nearby'.",
  "- 'timespan': Longer timespan tends to a wider relevance; e.g. 2h is more likely 'wider-region'.",
  "- 'occurrence': 'Recurring' events or event 'series' tend to a tighter relevance; e.g. recurring event is more likely relevant for a 'specific-location' or 'tight-nearby'.",
  "- 'occurrence': 'One time' events or 'single' events tend to a wider relevance like 'wider-region'.",
  "- 'occurrence': 'Opening hours' tend to a tighter relevance like 'tight-nearby'.",
  "- 'category': The category 'everyday-supply' tends to a tighter relevance like a 'specific-location' or 'tight-nearby'.",
  "- 'category': The category 'everyday-supply' combined with a timespan 'allday' or a short time tends to a very tight relevance 'specific-location'.",
  "- 'category': The category 'culture-tourism' tends to a wider relevance like a 'wider-region'.",
  "- 'category': The category 'community-life' tends to a nearby relevance like a 'formal-municipality' or 'tight-nearby'.",
  "- 'tags': Additional tags might define a more specific relevance.",
  "- 'tags': Tags for regional public traffic like ÖPNV, Bus, Rufbus, Fähre, Brücke tend to 'specific-location'.",
  "- 'tags': Tags for long distance transport like Bahn, Zug tend to 'tight-nearby'.",
  "- 'tags': Tags for a mobile supply like Auto, Wagen, Mobil tend to 'specific-location'.",
  "- 'tags': Tags with formal municipality relevance like Bürgermeister, Sprechstunde, Sitzung, Ausschuss is always 'formal-municipality'!",
];
